services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-gamebeater}
      POSTGRES_USER: ${DATABASE_USER:-gamebeater}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-gamebeater}
    ports:
      - ${DATABASE_PORT:-5432}:5432
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  backend:
    build:
      context: .
    ports:
      - ${API_PORT:-3000}:3000
      - ${PRISMA_STUDIO_PORT:-5555}:5555
    depends_on:
      - database
    volumes:
      - .:/app
    env_file:
      - .env
    command: corepack pnpm start:dev

  node: # This service it's only used to run git hooks
    build:
      context: .
    volumes:
      - .:/app

volumes:
  database_data:
